language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO_VERSION=1.5
install:
  - pip install -q Django==$DJANGO_VERSION coveralls
  - pip install --allow-all-external --allow-unverified elasticutils .
script:
  - coverage run --source=elastimorphic setup.py test
services:
  - elasticsearch
after_success:
  - coveralls
