language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
install:
  - pip install -q Django==$DJANGO_VERSION coveralls
  - python setup.py -q install
script:
  - DJANGO_SETTINGS_MODULE=travis_settings coverage run --source=elastimorphic setup.py test
services:
  - elasticsearch
after_success:
  - coveralls
